name: "Pull request workflow"

on:
  pull_request:
    branches:
      - develop
      - main
      - master

env:
  NODE_VERSION: 14.17

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: setup node
        uses: actions/setup-node@v2.5.0
        with:
          node-version: {{env.NODE_VERSION}}

      - name: checkout
        uses: actions/checkout@v2.4.0

      - uses: actions/cache@v2.1.7
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}-${{env.NODE_VERSION}}

      - name: install dependencies
        run: npm install

      - name: unit tests
        run: npm test